@host=http://localhost:7007

### get - ttt
{{host}}/ttt/1023?name=짱구

### get - users
GET {{host}}/users

### post - users
POST {{host}}/users
Content-Type: application/json

{
  "email": "csisgood@gmail.com",
  "name": "철수"
}

### delete - user
DELETE {{host}}/users/24

